### PR TITLE
Allow more dynamic version-bumping

### PR DESCRIPTION
**Pull request by jmuchovej**
Need to test this; but I believe it will work. Basing this off how homebrew Casks normally work – e.g. https://github.com/Homebrew/homebrew-cask/blob/master/Casks/notion.rb.

Will confirm this works, until then – hold-off on accepting. 😅

### CODE REVIEW

**Comment by xxxserxxx** [comment]
I like this change; did you verify that it works?  I also want to change the `update.sh` script.  If this works, then that script doesn't need the `sed` rule to update the URL.

**Comment by jmuchovej** [comment]
Like we talked about on xxxserxxx/gotop#60, there might be a better way than using the tap to do the installation. Right now `homebrew` will default to the `homebrew-core` installer before using a `tap`.

I may have actually given you incorrect information (my own inexperience with `homebrew`). 😕 It may be that the base repository needs a `Formula/gotop.rb` file. (To prevent cluttering `git` history, I think it may make sense to hold-off until we get some answers from the `homebrew` folks on `homebrew-core`?

**Comment by xxxserxxx** [comment]
GIT SQUASH

But, no, you're right.  Do you mind pursuing that?  I'm in #archlinux-aur trying to get the automated AUR updates nailed down.  I'd really also like to reach out to the deb, rpm, Alpine, slackware, and Nix maintainers.

**Comment by jmuchovej** [comment]
So, if we get `gotop` on `homebrew-core`, that's probably a solid start for getting proper pkgs on MacOS/Linux – thanks to `linuxbrew`? Obviously it's not official repo support, but still a better start than asking folks to `dpkg -i ...` or equivalent. 😅

**Comment by xxxserxxx** [comment]
There's also snap and flatpak, both of which have source hubs.  I opened #68 to track the various platforms.  There's a limit to how many of these I can actively help maintain, but any of the ones that can be automated I'm happy to set up workflows for.

Really, though -- thanks for taking the lead on the Homebrew conversation.  It helps.

**Review by xxxserxxx — APPROVED** [review]

**Pull request merged**
